defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:10.12.0

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install APT packages
          command: apt-get update -y && apt-get install jq -y
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install NPM dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run:
          name: Build
          command: npm run build
      - run:
          name: Pack
          command: .circleci/pack.sh
      - store_artifacts:
          path: ~/repo/package
      - persist_to_workspace:
          root: .
          paths:
            - build/
            - node_modules/
            - package.json
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm test
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - deploy:
          name: Deploy to NPM
          command: .circleci/deploy_to_npm.sh

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
      - deploy:
          context: npm_deployment
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
