
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: node:10.12.0
    steps:
      - checkout
      - run:
          name: Install APT packages
          command: apt-get update -y && apt-get install jq -y
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install NPM dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run:
          name: Build
          command: npm run build
      - run:
          name: Pack
          command: .circleci/pack.sh
      - store_artifacts:
          path: ~/repo/package
      - persist_to_workspace:
          root: .
          paths:
            - build/
            - node_modules/
            - package/
            - package.json
  test:
    working_directory: ~/repo
    docker:
      - image: node:10.12.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm test

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
